#+TITLE: pk_stl README
#+AUTHOR: Mateo Carreras

* Introduction

pk_stl is a Rust library for reading and writing STL files, and has no additional
dependencies other than the standard library. It can read and write both ASCII
and binary STL files.

** STL File Support

There are two main STL file formats: binary and ascii.

|       | Binary | ASCII |
|-------+--------+-------|
| Read  | Yes    | Yes   |
| Write | Yes    | Yes   |

Additionally, this library does not suppport any additional attributes attached
to the triangles or model, but this features will be in a future release. If
metadata from the header is needed, this library does provide access to the
contents of the header.

* Documentation

For full documentaiton run:

#+BEGIN_SRC bash
  cargo doc --open
#+END_SRC

Or visit [[https://docs.rs/pk_stl/latest/pk_stl]]

* Git Blame Ignore Revs
There is a ~.git-blame-ignore-revs~ file, which you can tell git about using:

#+BEGIN_SRC bash
git config blame.ignoreRevsFile .git-blame-ignore-revs
#+END_SRC

This tells git blame to skip over commits in that file, such as large code
reformats which would otherwise polute the history.
